### ISSUE TITLE
Issue with Firefox and HTML5 lookup error?

### ISSUE THREAD

**Issue by libelle** [onury/geolocator#21]
I have a simple locate script using the latest version of geolocator. When I run under Firefox 40.0 (on Mac OS), and either close the HTML5 location permission window or deny location access, I don't get a graceful degradation to IP-based lookup nor does it call my error function. It just seems to die quietly without any console messages.

I don't think I'm doing anything too egregiously stupid (famous last words!) because it works under Chrome/Mac, Safari/Mac, and IE8/Win7.

I tried setting up a jsfiddle, but was having problems with getting the external geolocator code to be included properly. So I set up a test case at http://www.fogbound.net/locate/

**Comment by onury** [comment]
@libelle, Geolocator.js will not fallback to IP unless the error callback of HTML5 geolocation is fired. This happens on **Firefox for Mac**, when the user clicks "**Not Now**" instead of "Never" when prompted. 

This is a bug filed in [bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=675533). Currently there is no workaround for this. We'll have to wait for Mozilla to fix this.
