### ISSUE TITLE
Only via HTML5 geolocation

### ISSUE THREAD

**Issue by sankar2389** [onury/geolocator#26]
I tried to create HTML5 geolocation by putting the `geolocator.locate()` function on `window.onload` directly. 

```
window.onload = function () {
                 var html5Options = { enableHighAccuracy: true, timeout: 6000, maximumAge: 0 },
                 ipFallbackIndex = chkFallback.checked ? cmbSource.selectedIndex : -1;
                 geolocator.locate(onGeoSuccess, onGeoError, 2, html5Options, 'map-canvas');
}
```

But there is no output, was anything wrong in it?

**Comment by onury** [comment]
- Did you define the handlers `onGeoSuccess` and `onGeoError`?
 - Did you grant Geolocation permission when prompted?

**Comment by sankar2389** [comment]
I'm a beginner, i don't have much knowledge about coding. I tried with your code to get the output of HTML5 geolocation instead of 
            `// Locate by IP on load`
            `geolocator.locateByIP(onGeoSuccess, onGeoError, 2, 'map-canvas');`
Also it ain't ask me to grand permission, but in some other examples similar to html5 geolocation prompted to grant permission.

**Comment by onury** [comment]
You should define the success and error handlers, otherwise you won't see any output.
See the full example in the [documentation](https://github.com/onury/geolocator/blob/master/README.md#usage). `onGeoSuccess` and `onGeoError` functions are defined right before `window.onload`.

`geolocator.locate()` method uses HTML5 Geolocation which prompts for user's permission (if not already granted).

`geolocator.locateByIP()` method is a `JSONP` call. This **won't** prompt for user's permission.

Also, if you want a map to be drawn/created; don't forget to include a `<div>` element with id `map-canvas` in your HTML. 
e.g. `<div id="map-canvas" style="width:600px;height:400px"></div>`

**Comment by sankar2389** [comment]
Thanks, now i can get the output.
