### ISSUE TITLE
GeoError happening

### ISSUE THREAD

**Issue by adrianobarroso** [onury/geolocator#62]
Hello everyone, I'm having this error which started a couple of days ago.

Have anyone gone through this error too?

fetch.js:229 `GET https://geoip.nekudo.com/shutdown net::ERR_ABORTED 404`

geolocator.js:957
```
{
  "name": "GeoError",
  "code": "UNKNOWN_ERROR",
  "message": "Could not load source at https://geoip.nekudo.com/api↵[object Event]",
  "stack": "GeoError: Could not load source at https://geoip.n…/libs/geolocator/2.1.3/geolocator.min.js:1:11824)"
}
```

**Comment by crackTheCode** [comment]
I also get this error. Is there a bug fix for that

**Comment by onury** [comment]
This is due to service change. Geolocator was using **_nekudo_** as the Geo IP source, now the service is changed. See [this notice](https://github.com/nekudocom/shiny_geoip/blob/master/README.md#readme).

The reason for using *nekudo* is that it was the only provider that supported HTTPS for free. Now it's changed to a service named *ipapi*. It still has a free plan but for HTTPS you need a paid plan. (_I have no affiliation with them._)

If you know of a free service that supports HTTPS, we can make that default for geolocator. 

For now, a workaround is to use the `.setGeoIPSource()` method to use another service. See [examples here](https://github.com/onury/geolocator/tree/master/src/geo-ip-sources).

**Comment by adrianobarroso** [comment]
Thanks @onury 

I changed my call to only `.locate()` and now is working 

Was getting the error using the method `.locateByIP()`
